### ISSUE TITLE
COMID 4781767 - observations, but no climate drivers

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#132]
I was selecting the climate drivers for the COMIDs where we have observations and 4781767 does not have any climate drivers. I think it's b/c it's at a divergence.
![image](https://user-images.githubusercontent.com/6943441/173972048-11d98f52-1886-40bc-a4df-065af6522aab.png)
![image](https://user-images.githubusercontent.com/6943441/173972065-6a9c59a2-efd6-4a4a-a13e-17e1b78e4bd4.png)

On this segment is site `01472185` which only has 3 observation days.

**Comment by lekoenig** [comment]
OK, yeah. That NHD flowline (COMID = 01472185) is a divergence, but divergent reaches can still have catchments (and therefore, climate drivers). This one doesn't because it's a zero-area flowline and so there's no associated catchment. We filter those out before writing the catchments gpkg file in drb-network-prep, but we haven't accounted for zero-area flowlines in the DO repo.

```
> # From drb-network-prep
> tar_load(p1_nhdv2reaches_sf)
> p1_nhdv2reaches_sf %>% 
+   filter(COMID == "4781767") %>% 
+   sf::st_drop_geometry() %>%
+   select(COMID, DIVERGENCE, STREAMCALC, STREAMORDE, AREASQKM)
# A tibble: 1 x 5
    COMID DIVERGENCE STREAMCALC STREAMORDE AREASQKM
    <int>      <int>      <int>      <int>    <dbl>
1 4781767          2          0          2        0
>
```

I'll take a look to see whether we should re-assign this site to a different flowline, or just omit it altogether since it only has 3 observation-days.
