### ISSUE TITLE
Matching to segments question

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#36]
From @lekoenig 
> Is 0.1 the default search_radius in nhdplusTools? Effectively, this nearest neighbor function will search within that radius (~10 km, I think) and if any segments are returned, we just want the closest one (e.g. maybe that line is 5 m or 5 km away). One thing I hadn't considered before is that with this approach, we may be incorrectly matching samples taken in small, headwater streams to larger river segments, which are the only ones represented by the PRMS lines. Do you think that's true?

> It looks like 50% of sites have offsets at or below 0.005 (~0.5 km, I think), but some can be higher, up to our max search_radius

![image](https://user-images.githubusercontent.com/6943441/147157593-6b860924-0114-4bd7-9613-f069739d57bd.png)

**Comment by lekoenig** [comment]
Currently, we're matching DO observations to reaches by looking for PRMS segments within 0.1 degrees of a given site. 0.1 degrees roughly corresponds to ~10 km, which is pretty far, especially considering we may be improperly snapping some headwater stream observations to the larger segments represented in the PRMS network. 

Here's one example segment (886_1) where we are currently matching 14 sites, some from NWIS and some from the WQP dataset. Segment 886_1 is a portion of the Schuylkill River, but we can see that several of the sites that got matched to 886_1 have different 'site names', suggesting that they are in fact, observations that were taken from smaller tributary streams and so probably aren't representative of seg id 886_1:


![matched_degrees](https://user-images.githubusercontent.com/8785034/157928861-9bb115d7-1aa9-43d2-85a8-ed84206c6bef.png)



![image](https://user-images.githubusercontent.com/8785034/157930813-d715fe7c-4257-4a90-a528-01e9a1cf2329.png)

**Comment by lekoenig** [comment]
Based on looking at these matched sites, I'd suggest we reduce our search radius. Within `2_process/src/match_sites_reaches.R` we use `nhdplusTools::get_flowline_index()` to find the nearest segment within a given search radius. Our `search_radius` argument is in degrees and this function returns an `offset` in degrees because the input flowlines (`p1_reaches_sf`) have a geographic CRS (WGS84). But degrees is kind of difficult to conceptualize (what's a reasonable cutoff if we don't use 0.1?). I think if we transform `p1_reaches_sf` to a projected CRS we could specify the `search_radius` in meters and also return our `offset` attribute in meters. 

We originally adapted `get_site_flowlines()` from other temperature repos (namely, [here](https://code.usgs.gov/wwatkins/national-site-reach/-/blob/master/R/match_sites_reaches.R) and [here](https://github.com/USGS-R/2wp-temp-observations/blob/174875b69c335436bf5acdeee8a53e5334ac72de/6_network/src/match_sites_reaches.R)). I noticed within those projects' yml files, `search_radius` is set at 500 (presumably this is m; see [lines](https://github.com/USGS-R/2wp-temp-observations/blob/174875b69c335436bf5acdeee8a53e5334ac72de/6_network.yml) 56-61 in the 2wp-temp repo). If I transform the spatial data and specify our search radius to 500 m, here's what the above example segment 886_1 looks like:

![matched_proj](https://user-images.githubusercontent.com/8785034/157935270-f9d2fec2-0e00-4a47-bc11-f6b2383cb72b.png)
![image](https://user-images.githubusercontent.com/8785034/157935718-c9102914-e943-49c1-99c7-dd57189e126e.png)

We're probably still picking up a few incorrectly-matched tribs (i.e. the sites that are between 250-500 m from the segment). We could therefore reduce our `search_radius` to 250 m, but there are also edge cases where larger rivers might not get snapped if they're wider than 250 m (e.g. issue [34](https://github.com/USGS-R/delaware-model-prep/issues/34) in delaware-model-prep).
