### ISSUE TITLE
Check correlation between temperature and DO predictions

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#48]
We are interested to see the correlation between model DO predictions and input air temperature in the Baseline model.

**Comment by jsadler2** [comment]
![do_preds_vs_temp](https://user-images.githubusercontent.com/6943441/154337089-a31abc2d-c833-4ed2-9275-28dbd5650c1c.png)

Here are plots of DO (predicted and observed) vs stream temperature. 

### The lower sites
The lower row of sites are doing quite well I'd say. I'm looking for places where the predicted DO at a certain temperature was above the observed DO at that same temp. These are the places where I _think_ the process guidance could help (as in if it's above 20 deg C, please don't predict DO above ~9 mg/l). 

I see a couple of these in the lower left - there is one prediction of almost 14 mg/l at ~8 deg C; another of ~11 mg/l at ~15 deg C. Those may have have been better with some guidance.

I also see a bit of cluster in the lower center plot at the warmest temps. Maybe those would be improved too.

### The upper sites
The upper two sites with obs are not doing as well. But they are _under_-estimating DO. My take on this possible constraint would be to basically put a "ceiling" on the DO predictions. So in these cases, I don't know that the guidance in terms of the temperature relationship would help improve things.

**Comment by amcarter** [comment]
Are these results from the model trained on DO data or one trained to predict GPP and ER and then calculate DO based on those? In the latter case, the temperature 'constraint' would come in in the calculation step, where we say that DO is the value at saturation (a function of temperature) - ER + GPP and could help to correct for over or underestimation.

>The upper two sites with obs are not doing as well. But they are under-estimating DO. 

We have water temperature for these sites, correct? I know that it is not an input to the model, but is it possible that at these upper sites the water temperature is actually lower than you would predict given the air temperature? That would mean that the model is learning the DO x temp relationship correctly, but making lower estimates than it should because it thinks the water temperature is higher than it is. Could you plot air temp x water temp for these sites and see if the relationship is different in the upper two?

**Comment by jsadler2** [comment]
Thanks for the thoughts, @amcarter 

>Are these results from the model trained on DO data or one trained to predict GPP and ER and then calculate DO based on those?

No. These are not trained to predict GPP and ER.

> Could you plot air temp x water temp for these sites and see if the relationship is different in the upper two?

Great idea. See plots below. (Sorry about the change in site order. I was doing this with UV data before an switched to DV which added a site - also added above).

The relationship _is_ different, but I'm not sure what to make of it. It's different in the opposite way that I was expecting. I was expecting the slope between air and water temp to be steeper for those two sites - that is, I thought a warmer air temperature would be warming the water _less_ leading to lower DO observations than predictions. Instead, if I'm understanding all of this right, it's the opposite, warmer air is warming the water _more_ in those sites than the others. So I would think that the model would have predicted cooler _water_ temperatures and therefore higher DO. But in fact, the predicted DO is _lower_ than observed DO.
![image](https://user-images.githubusercontent.com/6943441/155424434-03c684e1-d556-46e5-9382-9acee1b30663.png)


We are also seeing overall higher water temps at those two sites than the other three. 
![image](https://user-images.githubusercontent.com/6943441/155424064-27dbc821-2b3f-4259-b7a1-16fa91d327ee.png)

**Comment by lekoenig** [comment]
We'll want to similarly inspect these relationships for the NHD-version of the model, but I'm going to go ahead and close this issue for now.
