### ISSUE TITLE
How does DO saturation work?

### ISSUE THREAD

**Issue by jsadler2** [USGS-R/drb-do-ml#68]
Exposing my ignorance here. How does DO saturation work?

In my googling, I found this nice monogram (https://dep.wv.gov/WWE/getinvolved/sos/Documents/SOSKit/DOSaturation.pdf):

<img src=https://user-images.githubusercontent.com/6943441/158268340-e33ca307-e665-456d-9aea-1c7ef633ed4b.png width=500>

That makes me think that for every temperature, there is one and only one saturation DO concentration. For example, I draw a line between 10 deg C and 100% and I get something like 11 mg/l. That is what I would answer is the DO saturation concentration for 10 deg C. 

But ... when I look at the DO saturation values from here (https://www.sciencebase.gov/catalog/item/59eb9c0ae4b0026a55ffe389) and compare them to the water temperature values (also from that SB item), I get a _range_ of "DO.sat" for each "water.temp":

![image](https://user-images.githubusercontent.com/6943441/158268164-d56af89d-cf8d-470d-a296-2bd74dbd6c5f.png)

Why is that? Is it because of differences in air pressure?

**Comment by lekoenig** [comment]
I'll echo Alice here that DO-sat ~ _f_(temperature, pressure, salinity) so those different slopes are due to site differences in pressure (elevation). You can see this effect in the plot below where I've colored the sites in the Appling data release where altitude > 6000 ft:

![DO_sat_appling](https://user-images.githubusercontent.com/8785034/159732236-cabf52e5-30f3-4139-a644-2fb203b773f5.png)

Our sites in the DRB shouldn't vary too much in elevation (or salinity, although I don't expect salinity to be a strong driver of DO solubility in the range we would observe in freshwater streams of the DRB anyway), so if we just plot the Appling sites that overlap our target `p2_well_observed_sites` we see a tighter relationship between temperature and DO-sat:

![DO_sat](https://user-images.githubusercontent.com/8785034/159732793-5876c7f4-1154-4360-8f54-62dedf198c97.png)

**Comment by jsadler2** [comment]
Thank you, @amcarter and @lekoenig. That is very helpful. Also nice to know that it doesn't vary too much between sites in our study area.
